### PR TITLE
fix: data  not being copied to build folder when used as a dependency 

### LINKED ISSUE #4: Compilation error in file lib/mix/tasks/load_phone_data.ex
```elixir
== Compilation error in file lib/mix/tasks/load_phone_data.ex ==
** (CompileError) lib/mix/tasks/load_phone_data.ex:31: invalid literal nil in <<>>
    (elixir) src/elixir_bitstring.erl:19: :elixir_bitstring.expand/6
    (elixir) src/elixir_bitstring.erl:12: :elixir_bitstring.expand/4
    (elixir) expanding macro: Kernel.<>/2
    lib/mix/tasks/load_phone_data.ex:31: Mix.Tasks.PhoneNumber.LoadPhoneData.base_dir/0
    (elixir) expanding macro: Kernel.|>/2
    lib/mix/tasks/load_phone_data.ex:31: Mix.Tasks.PhoneNumber.LoadPhoneData.base_dir/0
```

### PR DESCRIPTION
**Pull request by m4hi2**
fixes #4

### CODE REVIEW

**Comment by mvalitov** [comment]
thanks for the contribution to the development of the project!

**Comment by m4hi2** [comment]
Hello @mvalitov, I see the package on hex.pm is not updated. it still refers to old code. :( can you please publish the updated code on hex.pm?

**Comment by mvalitov** [comment]
@m4hi2 sorry for the delays. updated the package

**Comment by m4hi2** [comment]
Thank you @mvalitov for creating this awesome lib and taking the time to update the hex package ❤️

**Pull request merged**
